### ISSUE TITLE
Get text

### ISSUE THREAD

**Issue by sruteesh** [dannyvassallo/insta_scrape#10]
Hello,
Great job with the gem. I am a python developer and am using this gem as I couldn't find better alternatives in python. Please let me know how do i get the text for every image. I saw some PR trying to do the same, but I dont see that reflecting in the output( even after **include_meta_data**: true ). I am a complete newbie to ruby, please respond.
Thanks.

**Comment by dannyvassallo** [comment]
Hey @sruteesh -- The text PR hasn't been merged into this gem yet. I simply haven't had the time. If that's something you need immediately, you can use his fork to get that feature although I do plan on making it part of the include_meta_data feature.

**Comment by dannyvassallo** [comment]
Text is now included in the new release of the gem.
