### ISSUE TITLE
User info for hashtag search

### ISSUE THREAD

**Issue by stanupab** [dannyvassallo/insta_scrape#13]
Hi! Thanks for a great package!

I was wondering if it's possible to get user info when using the hashtag search (InstaScrape.long_scrape_hashtag and InstaScrape.hashtag). Looks like each post has only:
@image
@link
@date
@text

I'd like to get the info about the user of each post as well.

Thank you!

**Comment by dannyvassallo** [comment]
@stanupab hey! Not currently with the way the gem is setup. In your fork, alter the "additional_meta" method and you may see the results you expect. If you get it, submit a PR and I'll look it over. If I get some time I'll try and make this another feature.

**Comment by dannyvassallo** [comment]
@stanupab working on a new release, adding username, hi res photo, and trying to add likes now.

**Comment by dannyvassallo** [comment]
@stanupab this is in the new release 1.1.3
