### ISSUE TITLE
Counts are not exact figure

### ISSUE THREAD

**Issue by Faisal-nfl** [dannyvassallo/insta_scrape#17]
When I get followers_count,
It gives like "2.9m" why not exact figure?

**Comment by dannyvassallo** [comment]
This is a scraper based on public data available from the UI on instagram's webapp. Please take a look at this picture and it should make sense.

<img width="760" alt="screen shot 2017-05-19 at 10 32 18 am" src="https://cloud.githubusercontent.com/assets/5847215/26252649/d27dac32-3c7e-11e7-8299-713f9e4dfed4.png">

Closing this though as it's not a real issue. If you'd like to create a PR to convert it to actual interger values I'm always willing to accept new/improved features.
