### ISSUE TITLE
undefined method `image' for nil:NilClass

### ISSUE THREAD

**Issue by fra0074** [dannyvassallo/insta_scrape#23]
on InstaScrape.user_info_and_posts(username) I got this error:

NoMethodError: undefined method `image' for nil:NilClass
from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/insta_scrape-1.1.4/lib/insta_scrape.rb:191:in `log_posts'

Thanks

**Comment by dannyvassallo** [comment]
Can I see the code you are using?

**Comment by fra0074** [comment]
I install your Gem on a clean new project, and from console I am calling:

r = InstaScrape.user_info_and_posts("foofighters") --> it works with this example

but with another username, like mine for example

r = InstaScrape.user_info_and_posts("fraeccl") --> NoMethodError: undefined method image' for nil:NilClass from
 /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/
 gems/insta_scrape-1.1.4/lib/insta_scrape.rb:191:inlog_posts'

**Comment by dannyvassallo** [comment]
Is your instagram profile private?

**Comment by fra0074** [comment]
yes it is, means the scrape does not work with private profile?

**Comment by dannyvassallo** [comment]
The scraper can't work with a private profile. It's a scraper. Anything it
needs has to be public. That's the nature of this tool.

**Comment by dannyvassallo** [comment]
Closing this as it's not an actual problem.
