### ISSUE TITLE
Instagram Public_content vs scrape?

### ISSUE THREAD

**Issue by trevynmeyer** [dannyvassallo/insta_scrape#26]
Sorry to troll you about insta_scrape, but I had a question.  I work with a gorup who is unable to get granted public_content to pull post data of specific hashtags.  Is that what your script does? Any tips on getting approved for public content? Any issues you have had with getting IP blocked or anything?  Thanks in advance..

Trevyn

**Comment by dannyvassallo** [comment]
No probelm. That's exactly what this does. I've had no issues with being
banned or blocked either. As far as I know, you'll be fine.
