### ISSUE TITLE
Returning 'created at' date from posts

### ISSUE THREAD

**Issue by oguzcanhuner** [dannyvassallo/insta_scrape#6]
Hey, thanks for creating this gem; it's been really useful!

It would be great to scrape the time that posts were created at. I'm happy to submit a PR with that change if that's okay with you :)

**Comment by dannyvassallo** [comment]
Absolutely! Thanks for extending your help. Just send me the PR and I'll review it. If you can write supporting tests as well, that would be great.

Looking forward to your contribution!

**Comment by dannyvassallo** [comment]
Merged -- will deploy a new release to rubygems after updating the readme.
